default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: wurst
  password: wurst

development:
  <<: *default
  database: wurst_development

test:
  <<: *default
  database: wurst_test

production:
  <<: *default
  database: wurst_production
  password: <%= ENV["WURST_POSTGRESQL_PASSWORD"] %>
